### ISSUE TITLE
Unable to analyze NodeJS Project

### ISSUE THREAD

**Issue by NickCarton** [aosapps/drone-sonar-plugin#4]
When running drone-sonar-plugin against my nodejs project, I get the following error.
```
ERROR: Failed to get Node.js version. No CSS files will be analyzed.
--
java.io.IOException: Cannot run program "node": error=2, No such file or directory
```

Is there someway to account for this?

**Comment by NickCarton** [comment]
Just found out that we need to specify `aosapps/drone-sonar-plugin:1.0`
`latest` tag on docker hub has not been updated for 1.0

**Comment by roganw** [comment]
> Just found out that we need to specify `aosapps/drone-sonar-plugin:1.0`
> `latest` tag on docker hub has not been updated for 1.0

The tag has been updated.
