### ISSUE TITLE
Should be able to analyze default sonar projects

### ISSUE THREAD

**Issue by NickCarton** [aosapps/drone-sonar-plugin#5]
Version 1.0 of drone-sonar-plugin does not support

- dotnet core
- typescript 

I believe that by default, this plugin should support the following project types as listed on the sonarqube web page:
    ABAP
    Apex
    C/C++
    C#
    CSS
    COBOL
    Flex
    Go
    HTML
    Java
    JavaScript
    Kotlin
    Objective-C
    PL/SQL
    PL/I
    PHP
    Python
    RPG
    Ruby
    Scala
    Swift
    T-SQL
    TypeScript
    VB.NET
    VB6
    XML

**Comment by saitho** [comment]
The latest version of sonar-scanner is  4.2.0.1873. I think upgrading to that would enable support for the mentioned languages.
