### ISSUE TITLE
SonarQube server [] can not be reached

### ISSUE THREAD

**Issue by aleksey005** [aosapps/drone-sonar-plugin#6]
Hello

I'm trying to run drone sonarqube plugin get an error.

SonarQube 7.6.0.21501
drone 0.8
Enviroment Rancher 2.2.2

pipeline:
  code-analysis:
    image: aosapps/drone-sonar-plugin
    secrets: [ sonar_host, sonar_token ]

==> Code Analysis Result: INFO: Scanner configuration file: /bin/sonar-scanner-3.3.0.1492/conf/sonar-scanner.properties
INFO: Project root configuration file: /drone/src/-------/-----/--------/sonar-project.properties
INFO: SonarQube Scanner 3.3.0.1492
INFO: Java 1.8.0_171 Oracle Corporation (64-bit)
INFO: Linux 4.15.0-46-generic amd64
INFO: User cache: /root/.sonar/cache
ERROR: SonarQube server [] can not be reached
INFO: ------------------------------------------------------------------------
INFO: EXECUTION FAILURE
INFO: ------------------------------------------------------------------------
INFO: Total time: 0.645s
INFO: Final Memory: 3M/59M
INFO: ------------------------------------------------------------------------
ERROR: Error during SonarQube Scanner execution
ERROR: Unable to execute SonarQube
ERROR: Caused by: Fail to get bootstrap index from server
ERROR: Caused by: Expected URL scheme 'http' or 'https' but no colon was found
ERROR: 
ERROR: Re-run SonarQube Scanner using the -X switch to enable full debug logging.

exit status 1

**Comment by roganw** [comment]
> ERROR: SonarQube server [] can not be reached

Please check the config of *sonar_host* .

**Comment by aleksey005** [comment]
sonar_host exist secrets drone in repository settings sonar_host http://10.1.1.105:9000

**Comment by jamesbarnett91** [comment]
@aleksey005 Looks like you are using the Drone v0.8 pipeline syntax, so you'll want to pull the 0.8 tag of the plugin. e.g.
```
  code-analysis:
    image: aosapps/drone-sonar-plugin:0.8
    secrets: [sonar_host, sonar_token]
```

I think the 1.0 image (which is also tagged latest) expects the secrets passed in the new 1.0 style syntax and so doesn't pick up the host.
